# Defaults
defaults:
  - 
    scope:
      type: "posts"
      path: "_posts"
    values:
        is_post: true
        layout: posts
        author: "itsnatoriousb"
  -
    scope:
      type: pages
      path: "_pages"
    values:
        is_post: false
        layout: default
        author: "itsnatoriousb"
        
# Site Settings
name: BOCW Asset Directory
title: BOCW Asset Directory | A site to help locating game assets
description: A site to help easily browse and locate content for usage
tags:
  - black ops
  - black ops cold war
  - call of duty black ops
  - call of duty black ops cold war
  - call of duty
  - call of duty modding
  - call of duty mapping
email: itsnatoriousb@gmail.com
disqus_username: natoriousb
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Tutorials
    url: /tutorials
  - title: Weapons
    url: /weapons

# Social Media Settings
# Remove the item if you don't need it
github_username: itsnatoriousb
twitter_username: itsnatoriousb


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: false
two_columns_layout: true


# Gallery Settings
gallery:
  dir: _photos              # Path to the gallery
  symlink: true            # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "Photos"           # Title for gallery index page
  title_prefix: "Photos: "  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field: "date_time"   # How to sort galleries on the index page.
                            # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: 400                  # max width of thumbnails (in pixels)
    y: 400                  # max height of thumbnails (in pixels)
  # The following options are for individual galleries.
  galleries:
    chile_trip:
      best_image: IMG_1068.JPG  # The image to show on the gallery index page. Defaults to the last image.
    japan_trip:
      best_image: IMG_0690.JPG
      name: "日本の旅"       # Defaults to directory name, replacing _ with spaces & capitalizing words.
    awesome_stuff:
      best_image: snaileo_gonzales.jpg
      sort_reverse: true    # Reverse sort images in gallery.
    secret_stuff:
      hidden: true          # Don't show this gallery on the index page. People must guess the URL.
    with_info:
      info:
        desc: "Gallery Description" # Info fields can be used in custom templates.

# Advanced Settings
baseurl: "/bocw-asset-directory" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: none
permalink: /:categories/:title
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: true
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content
  - jekyll-gallery-generator
  - jekyll-spaceship

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]